version: '3.4'

services:
  identity:
    build:
      context: .
      dockerfile: src/Identity/KnowYourCustomer.Identity/Dockerfile
    ports:
      - "5000:80"
    environment:
      - "ConnectionStrings:IdentityServerDb=Server=sqlserver;Database=KnowYourCustomer.IdentityDb;User Id=sa;Password=Pass_w0rd;Application Name=Kyc.Identity"
    depends_on:
      - sqlserver
    restart: on-failure

  kyc:
    image: ${DOCKER_REGISTRY-}kyc
    build:
      context: .
      dockerfile: src/Kyc/KnowYourCustomer.Kyc.Host/Dockerfile
    ports:
      - "5001:80"
    environment:
      - "IdentityServerUrl=http://identity"
    depends_on:
      - identity
      - sqlserver
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      - MSSQL_SA_PASSWORD=Pass_w0rd
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1401:1433"
    container_name: sqlserver