// <auto-generated />
using System;
using KnowYourCustomer.Kyc.Data.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KnowYourCustomer.Kyc.Host.Infrastructure.Migrations
{
    [DbContext(typeof(KycDbContext))]
    partial class KycDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KnowYourCustomer.Kyc.Data.Contracts.Entities.KycDocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Document");

                    b.Property<Guid>("KycId");

                    b.Property<DateTime>("UploadedOn");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("KycDocuments");
                });

            modelBuilder.Entity("KnowYourCustomer.Kyc.Data.Contracts.Entities.KycEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("RequestDate");

                    b.Property<int>("Status");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Kyc");
                });

            modelBuilder.Entity("KnowYourCustomer.Kyc.Data.Contracts.Entities.KycOperationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("KycId");

                    b.Property<int>("Operation");

                    b.Property<int>("Provider");

                    b.Property<DateTime>("TimeOperation");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("KycOperations");
                });
#pragma warning restore 612, 618
        }
    }
}
